import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import TopNav from "@/components/navbar/TopNav";
import { NextUIProvider } from "@nextui-org/react";
import { ToastContainer } from "react-toastify";
import { auth } from "@/auth";
import { useNotificationChannel } from "./hooks/useNotificationChannel";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "date next",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  const userId = session?.user?.id || null
  const profileComplete = session?.user.profileComplete as boolean
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* @ts-ignore */}
        <Providers profileComplete={profileComplete} userId={userId}>
          <NextUIProvider>
            <TopNav></TopNav>
            <ToastContainer position="top-right" hideProgressBar>
            </ToastContainer>
            {children}
          </NextUIProvider>
        </Providers>
      </body>
    </html>
  );
}



//  <main className="container mx-auto">
//             <ToastContainer position="top-right" hideProgressBar></ToastContainer>
//             {children}
//           </main>
